import os
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from datetime import datetime

def generate_prediction_report(user, result, output_path):
    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    name = user.name if user else "User"
    email = user.email if user else "N/A"
    date_str = datetime.utcnow().strftime("%d %B %Y, %H:%M UTC")
    result_text = "Positive (High Risk)" if result == "Positive" else "Negative (Low Risk)"

    c = canvas.Canvas(output_path, pagesize=A4)
    width, height = A4

    c.setFont("Helvetica-Bold", 18)
    c.drawString(80, height - 100, "🫀 Heart Disease Prediction Report")

    c.setFont("Helvetica", 12)
    c.drawString(80, height - 150, f"Name: {name}")
    c.drawString(80, height - 170, f"Email: {email}")
    c.drawString(80, height - 190, f"Date: {date_str}")
    c.setFont("Helvetica-Bold", 13)
    c.drawString(80, height - 230, f"Prediction Result: {result_text}")

    c.setFont("Helvetica-Oblique", 10)
    c.drawString(80, height - 270, "Generated by HeartCare AI — Stay healthy!")

    c.save()
